### ISSUE TITLE
no git tag for 1.0.0

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-pagination#20]
1.0.0 was released on npmjs 2 month ago

![image](https://user-images.githubusercontent.com/16578570/68071856-35fda500-fd7f-11e9-8620-b752e6931138.png)

But has never been released on github https://github.com/hexojs/hexo-pagination/releases

![image](https://user-images.githubusercontent.com/16578570/68071872-46158480-fd7f-11e9-943a-4317a69d0d89.png)

It is in the master branch but there is no 1.0.0 tag

**Comment by noraj** [comment]
similar to https://github.com/hexojs/hexo-deployer-git/issues/150

**Comment by YoshinoriN** [comment]
@noraj 
Thank you for your report as well :)
I just added 1.0.0 tag

> https://github.com/hexojs/hexo-pagination/releases/tag/1.0.0
