### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-pagination#21]
Could you provide a changelog either in CHANGELOG.md or https://github.com/hexojs/hexo-pagination/releases

There is no such a file or notes in the release section currently

![image](https://user-images.githubusercontent.com/16578570/68071896-c0460900-fd7f-11e9-893d-f9fcc9449712.png)

0.1.0 -> 1.0.0 is a major change but we don't know what changed without reading the commits

**Comment by uiolee** [comment]
It looks outdated and I am going to close this.

If problem still exits, please **reopen** it.

-------

Now we work through PRs, so that change logs can be automatically generated when draft releases.
