### ISSUE TITLE
Generates the first index.html without blog directory 

### ISSUE THREAD

**Issue by kiarafbickers** [hexojs/hexo-pagination#37]
When you modify the root _config.yml file to include:

```
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```

It creates blog pages without the first numbered index.

```
INFO  Generated: index.html
INFO  Generated: blog/2/index.html
INFO  Generated: blog/3/index.html
INFO  Generated: blog/4/index.html
INFO  Generated: blog/5/index.html
```

The first blog page should be `blog/1/index.html` instead of `index.html`.

**Comment by stevenjoezhang** [comment]
See https://github.com/hexojs/hexo-pagination/blob/b55476aba501102b6f7e86b61713b125962d8b39/lib/pagination.js#L27
